'use strict';
const $=id=>document.getElementById(id), KEY='kid-storybook.v1';
const defaults={font:'sans',color:'#233342',size:32,x:8,y:65,width:84,lineHeight:1.6,paragraphGap:12,align:'left',backdrop:true,showText:true,boxColor:'#ffffff',boxOpacity:85,borderColor:'#233342',borderWidth:0};
const fonts={sans:'system-ui, sans-serif',serif:'"Noto Serif TC", "Songti TC", serif',kai:'"BiauKai", "KaiTi", serif'};
const uid=()=>crypto.randomUUID();
const newPage=()=>({id:uid(),title:'新的一頁',text:'',style:{...defaults},image:null,fit:'contain'});
const newBook=title=>({id:uid(),title,pages:[newPage()]});
let state,db,imageURL,renderToken=0,dragId=null,toastTimer,animation;
function toast(message){$('toast').textContent=message;$('toast').style.display='block';clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').style.display='none',4500)}
function book(){return state.books.find(b=>b.id===state.bookId)}
function page(){return book().pages.find(p=>p.id===state.pageId)}
function save(){try{localStorage.setItem(KEY,JSON.stringify(state));$('saveStatus').textContent='✓ 已儲存於此瀏覽器';return true}catch(e){$('saveStatus').textContent='儲存失敗，請匯出備份';toast('瀏覽器儲存空間不足或無法存取，請立即匯出備份。');return false}}
function imageStore(mode,action){return new Promise((resolve,reject)=>{if(!db)return reject(new Error('圖片儲存無法使用'));const tx=db.transaction('images',mode),req=action(tx.objectStore('images'));tx.oncomplete=()=>resolve(req?.result);tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error)})}
function validate(data){if(data?.version!==1||!Array.isArray(data.books)||!data.books.length)throw Error('備份格式不正確');const ids=new Set();for(const b of data.books){if(typeof b.id!=='string'||ids.has(b.id)||typeof b.title!=='string'||!Array.isArray(b.pages)||!b.pages.length)throw Error('故事資料不完整');ids.add(b.id);for(const p of b.pages){if(typeof p.id!=='string'||ids.has(p.id)||typeof p.title!=='string'||typeof p.text!=='string')throw Error('頁面資料不完整');ids.add(p.id);p.style={...defaults,...p.style};if(!fonts[p.style.font])p.style.font='sans';if(!/^#[0-9a-f]{6}$/i.test(p.style.color))p.style.color=defaults.color;for(const [k,min,max] of [['boxOpacity',0,100],['borderWidth',0,12],['size',12,96],['x',0,95],['y',0,95],['width',10,100],['lineHeight',.8,3],['paragraphGap',0,80]]){if(!Number.isFinite(+p.style[k]))throw Error('文字樣式不正確');p.style[k]=Math.min(max,Math.max(min,+p.style[k]))}if(!['left','center','right'].includes(p.style.align))p.style.align='left';for(const k of ['boxColor','borderColor'])if(!/^#[0-9a-f]{6}$/i.test(p.style[k]))p.style[k]=defaults[k];p.style.backdrop=!!p.style.backdrop;p.fit=p.fit==='cover'?'cover':'contain';if(p.image&&(typeof p.image.id!=='string'||typeof p.image.name!=='string'))throw Error('圖片資料不完整')}}return data}
function renderLibrary(){$('books').replaceChildren();for(const b of state.books){const section=document.createElement('div');section.className='book';const btn=document.createElement('button');btn.className='book-button'+(b===book()?' active':'');btn.textContent='▤  '+b.title;btn.onclick=()=>{state.bookId=b.id;state.pageId=b.pages[0].id;save();render()};const bookRow=document.createElement('div');bookRow.className='book-actions';const trash=trashButton('刪除故事書「'+b.title+'」',()=>deleteBook(b));bookRow.append(btn,trash);section.append(bookRow);if(b===book()){const list=document.createElement('div');list.className='pages';for(const [i,p] of b.pages.entries()){const row=document.createElement('div');row.className='page-row'+(p===page()?' active':'');row.dataset.pageId=p.id;row.draggable=true;const handle=document.createElement('span');handle.className='handle';handle.textContent='⠿';handle.title='拖曳排序';handle.onpointerdown=e=>{e.preventDefault();handle.setPointerCapture(e.pointerId);dragId=p.id};handle.onpointerup=e=>{if(!dragId)return;const target=document.elementFromPoint(e.clientX,e.clientY)?.closest('[data-page-id]');if(target)reorder(dragId,target.dataset.pageId);dragId=null};const pick=document.createElement('button');pick.className='page-select';pick.textContent=String(i+1).padStart(2,'0')+'  '+p.title;pick.onclick=()=>selectPage(p.id);row.append(handle,pick,trashButton('刪除第 '+(i+1)+' 頁',()=>deletePage(p.id)));for(const [symbol,delta,label] of [['↑',-1,'上移'],['↓',1,'下移']]){const move=document.createElement('button');move.className='reorder';move.textContent=symbol;move.setAttribute('aria-label',label+'第 '+(i+1)+' 頁');move.disabled=i+delta<0||i+delta>=b.pages.length;move.onclick=()=>reorder(p.id,b.pages[i+delta].id);row.append(move)}row.ondragstart=e=>{dragId=p.id;e.dataTransfer.setData('text/plain',p.id);e.dataTransfer.effectAllowed='move'};row.ondragover=e=>{e.preventDefault();row.classList.add('over')};row.ondragleave=()=>row.classList.remove('over');row.ondrop=e=>{e.preventDefault();reorder(dragId||e.dataTransfer.getData('text/plain'),p.id);dragId=null};row.ondragend=()=>{dragId=null;document.querySelectorAll('.over').forEach(el=>el.classList.remove('over'))};list.append(row)}const add=document.createElement('button');add.className='add-page';add.textContent='＋ 新增頁面';add.onclick=()=>{const p=newPage();b.pages.push(p);state.pageId=p.id;save();render()};list.append(add);section.append(list)}$('books').append(section)}}
function reorder(from,to){const pages=book().pages,a=pages.findIndex(p=>p.id===from),b=pages.findIndex(p=>p.id===to);if(a<0||b<0||a===b)return;pages.splice(b,0,pages.splice(a,1)[0]);save();renderLibrary();renderPager()}
function renderPager(){const i=book().pages.indexOf(page());$('pageNumber').textContent=`${i+1} / ${book().pages.length} 頁`;$('pageBadge').textContent=String(i+1).padStart(2,'0');$('prev').disabled=i===0;$('next').disabled=i===book().pages.length-1}
function selectPage(id){const old=book().pages.indexOf(page());state.pageId=id;const direction=book().pages.indexOf(page())>=old?1:-1;save();render();animation?.cancel();if(!matchMedia('(prefers-reduced-motion: reduce)').matches)animation=$('scene').animate([{transform:`translateX(${direction*100}%)`,opacity:.3},{transform:'translateX(0)',opacity:1}],{duration:280,easing:'ease-out'})}
function stylePreview(){paintAllLayers();const s=textTarget().style;for(const k of ['size','x','y','width','boxOpacity'])$(k+'Value').textContent=s[k]+(k==='size'?' px':'%')}
async function getImageBlob(image){if(image.asset){if(!/^stories\/(?:first-time\/images\/scene[0-9.]+\.png|saved\/images\/[a-f0-9]{64}\.(?:png|jpg|webp|gif))$/.test(image.asset))throw Error('圖片路徑不正確');const response=await fetch(image.asset+(/scene(2|15\.5)\.png$/.test(image.asset)?'?revision=gate-scene1-v2':''));if(!response.ok)throw Error('圖片下載失敗');return response.blob()}return imageStore('readonly',s=>s.get(image.id))}
async function renderImage(){const token=++renderToken,p=page();$('art').style.display='none';$('emptyArt').style.display=(p.image||p.layers?.length)?'none':'flex';$('art').removeAttribute('src');if(imageURL){URL.revokeObjectURL(imageURL);imageURL=null}$('previewImage').disabled=$('removeImage').disabled=!p.image;$('imageInfo').textContent=p.image?p.image.name:'尚未上傳圖片';$('sceneStatus').textContent=p.image?'已加入原始圖片':(p.imageStatus||'尚未上傳圖片');if(!p.image)return;try{const blob=await getImageBlob(p.image);if(token!==renderToken)return;if(!blob)throw Error('找不到原始圖片');imageURL=URL.createObjectURL(blob);$('art').src=imageURL;$('art').style.objectFit=p.fit;$('art').style.display='block'}catch(e){if(token===renderToken)toast('無法讀取圖片，請重新上傳。')}}
function render(){page().style={...defaults,...page().style};renderSize();$('overview').value=book().overview||'';$('sceneNotes').value=page().scene||'';$('sceneStatus').textContent=page().image?'已加入原始圖片':(page().imageStatus||'尚未上傳圖片');$('storyReferences').hidden=!book().source;$('bookHeading').textContent=book().title;$('pageTitle').value=page().title;syncLayerSelection();$('storyText').value=textTarget().text;for(const k of Object.keys(defaults)){if(typeof defaults[k]==='boolean')$(k).checked=textTarget().style[k];else $(k).value=textTarget().style[k]}$('fit').value=page().fit;renderLibrary();renderPager();stylePreview();renderImage()}
async function askName(title,value=''){$('dialogTitle').textContent=title;$('nameInput').value=value;$('nameDialog').showModal();$('nameInput').focus();return new Promise(resolve=>$('nameDialog').addEventListener('close',()=>resolve($('nameDialog').returnValue==='ok'?$('nameInput').value.trim():null),{once:true}))}
$('newBook').onclick=async()=>{const title=await askName('新增故事書');if(!title)return;const b=newBook(title);state.books.push(b);state.bookId=b.id;state.pageId=b.pages[0].id;save();render()};
$('renameBook').onclick=async()=>{const title=await askName('重新命名故事書',book().title);if(title){book().title=title;save();render()}};
$('overview').oninput=e=>{book().overview=e.target.value;save()};$('sceneNotes').oninput=e=>{page().scene=e.target.value;save()};
$('pageTitle').oninput=e=>{page().title=e.target.value;save();renderLibrary()};$('storyText').oninput=e=>{textTarget().text=e.target.value;save();stylePreview()};
for(const k of Object.keys(defaults))$(k).oninput=e=>{const value=typeof defaults[k]==='boolean'?e.target.checked:typeof defaults[k]==='number'?Number(e.target.value):e.target.value;if(typeof value==='number'&&(!e.target.validity.valid||e.target.value===''))return;textTarget().style[k]=value;save();stylePreview()};
$('resetStyle').onclick=()=>{textTarget().style={...defaults};save();render()};$('fit').onchange=e=>{page().fit=e.target.value;$('art').style.objectFit=page().fit;save()};
$('prev').onclick=()=>selectPage(book().pages[book().pages.indexOf(page())-1].id);$('next').onclick=()=>selectPage(book().pages[book().pages.indexOf(page())+1].id);
$('toggle').onclick=()=>{state.collapsed=!state.collapsed;applyCollapse();save()};function applyCollapse(){document.body.classList.toggle('collapsed',state.collapsed);$('toggle').setAttribute('aria-expanded',String(!state.collapsed));$('toggle').setAttribute('aria-label',state.collapsed?'展開左欄':'收折左欄')}
$('deletePage').onclick=()=>deletePage(page().id);
$('imageInput').onchange=async e=>{const file=e.target.files[0],p=page();e.target.value='';if(!file)return;if(!['image/png','image/jpeg','image/webp','image/gif'].includes(file.type)){toast('請選擇 PNG、JPEG、WebP 或 GIF 圖片。');return}try{const test=await createImageBitmap(file);test.close();const id=uid();await imageStore('readwrite',s=>s.put(file,id));p.image={id,name:file.name,type:file.type,size:file.size};save();if(page()===p)renderImage()}catch(e){toast('圖片儲存失敗，請確認圖片有效且瀏覽器空間足夠。')}};
$('removeImage').onclick=()=>{if(confirm('移除此頁圖片？')){page().image=null;save();renderImage()}};
$('previewImage').onclick=()=>{if(imageURL){$('originalImage').src=imageURL;$('imageDialog').showModal()}};$('closeImage').onclick=()=>$('imageDialog').close();
const dataURL=blob=>new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(blob)});
$('export').onclick=async()=>{try{const copy=JSON.parse(JSON.stringify(state)),images={};for(const b of copy.books)for(const p of b.pages)for(const ref of pageImages(p)){const blob=await getImageBlob(ref);if(!blob)throw Error('圖片遺失');images[ref.id]=await dataURL(blob)}const url=URL.createObjectURL(new Blob([JSON.stringify({...copy,images},null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='故事工房-'+new Date().toISOString().slice(0,10)+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('已匯出所有故事與原始圖片。')}catch(e){toast('匯出失敗：'+e.message)}};
$('import').onclick=()=>$('importInput').click();$('importInput').onchange=async e=>{const file=e.target.files[0];e.target.value='';if(!file)return;try{const incoming=validate(JSON.parse(await file.text())),prepared=[];for(const b of incoming.books){b.id=uid();for(const p of b.pages){p.id=uid();for(const ref of pageImages(p)){const raw=incoming.images?.[ref.id];if(typeof raw!=='string'||!/^data:image\/(png|jpeg|webp|gif);base64,/.test(raw))throw Error('備份缺少有效圖片');const blob=await (await fetch(raw)).blob();const bitmap=await createImageBitmap(blob);bitmap.close();ref.id=uid();delete ref.asset;prepared.push([ref.id,blob])}}}for(const [id,blob] of prepared)await imageStore('readwrite',s=>s.put(blob,id));state.books.push(...incoming.books);state.bookId=incoming.books[0].id;state.pageId=incoming.books[0].pages[0].id;save();render();toast('已加入備份中的故事書。')}catch(e){toast('無法匯入：'+e.message)}};
const trashIcon='<svg viewBox="0 0 24 24" width="16" height="16" fill="none" stroke="currentColor" stroke-width="1.8" aria-hidden="true"><path d="M3 6h18M9 6V3h6v3M5 6l1 15h12l1-15M10 10v7m4-7v7"/></svg>';
async function confirmDelete(message){$('deleteMessage').textContent=message;$('deleteDialog').returnValue='cancel';$('deleteDialog').showModal();return new Promise(resolve=>$('deleteDialog').addEventListener('close',()=>resolve($('deleteDialog').returnValue==='delete'),{once:true}))}
function trashButton(label,action){const b=document.createElement('button');b.className='trash';b.innerHTML=trashIcon;b.setAttribute('aria-label',label);b.title=label;b.onclick=action;return b}
async function deletePage(id){if(!await confirmDelete('確定刪除此頁？'))return;const pages=book().pages,i=pages.findIndex(p=>p.id===id);if(i<0)return;pages.splice(i,1);if(!pages.length)pages.push(newPage());if(state.pageId===id)state.pageId=pages[Math.min(i,pages.length-1)].id;save();render()}
async function deleteBook(b){if(!await confirmDelete('確定刪除「'+b.title+'」與全部頁面？'))return;state.deletedBooks=[...new Set([...(state.deletedBooks||[]),b.id])];state.books=state.books.filter(x=>x!==b);if(!state.books.length)state.books.push(newBook('我的第一本故事書'));if(state.bookId===b.id){state.bookId=state.books[0].id;state.pageId=state.books[0].pages[0].id}save();render()}
const pageSizes=['2048x1536','1024x768','1600x1200','1920x1080','1536x2048'];
function renderSize(){if(!pageSizes.includes(book().pageSize))book().pageSize='2048x1536';const [w,h]=book().pageSize.split('x');$('pageSize').value=book().pageSize;$('viewport').style.aspectRatio=w+'/'+h;$('dimensionLabel').textContent=w+' × '+h+' px';}
$('pageSize').onchange=e=>{book().pageSize=e.target.value;renderSize();save()};
$('deletePage').innerHTML=trashIcon+' 刪除此頁';
async function startEditor(){try{db=await new Promise((resolve,reject)=>{const r=indexedDB.open('kid-storybook',1);r.onupgradeneeded=()=>r.result.createObjectStore('images');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}catch(e){toast('圖片儲存無法使用；文字仍可編輯。')}try{const raw=localStorage.getItem(KEY);if(raw)state=validate(JSON.parse(raw))}catch(e){$('saveStatus').textContent='原資料讀取失敗';toast('儲存資料無法讀取，請從備份匯入。');return}const freshLibrary=!state;if(!state){const b=newBook('我的第一本故事書');b.pages[0].title='故事的開始';state={version:1,books:[b],bookId:b.id,pageId:b.pages[0].id,collapsed:false}}const bundled=window.STORY_LIBRARY||[];let added=false;for(const b of bundled){if(!state.books.some(existing=>existing.id===b.id)&&!state.deletedBooks?.includes(b.id)){state.books.push(JSON.parse(JSON.stringify(b)));added=true}}for(const source of bundled){const existing=state.books.find(b=>b.id===source.id);if(!existing)continue;for(const template of source.pages){const p=existing.pages.find(p=>p.id===template.id);if(p&&!p.bundledImageVersion){if(!p.image&&template.image){p.image=JSON.parse(JSON.stringify(template.image));p.imageStatus=template.imageStatus;if(template.style.showText===false)p.style.showText=false}p.bundledImageVersion=1}}}if(added&&freshLibrary){const b=state.books.find(b=>b.id===bundled[0].id)||state.books[0];state.bookId=b.id;state.pageId=b.pages[0].id}if(!book())state.bookId=state.books[0].id;if(!page())state.pageId=book().pages[0].id;applyCollapse();render();save()}
