'use strict';
let selectedLayer='base',layerPageId,layerGesture;
const layerURLs=new Map();
const layerDefaults={x:15,y:20,width:40,height:20,rotation:0,keepAspect:true};
function prepareLayers(p){
  p.layers=Array.isArray(p.layers)?p.layers:[];
  p.layers=p.layers.filter(l=>l&&typeof l.id==='string'&&['text','bubble','image'].includes(l.type));
  for(const l of p.layers){l.style={...defaults,...layerDefaults,...l.style};l.text=typeof l.text==='string'?l.text:'';normalizeLayerStyle(l.style)}
  p.style={...defaults,rotation:0,height:0,...p.style};normalizeLayerStyle(p.style);
  const ids=['base',...p.layers.map(l=>l.id)];p.layerOrder=[...new Set([...(Array.isArray(p.layerOrder)?p.layerOrder:[]),...ids])].filter(id=>ids.includes(id));
}
function normalizeLayerStyle(s){for(const [k,min,max,fallback] of [['x',0,95,8],['y',0,95,20],['width',2,100,40],['height',0,100,0],['rotation',-180,180,0],['size',12,96,32],['lineHeight',.8,3,1.6],['paragraphGap',0,80,12],['boxOpacity',0,100,85],['borderWidth',0,12,0]])s[k]=Number.isFinite(+s[k])?Math.min(max,Math.max(min,+s[k])):fallback;for(const k of ['color','boxColor','borderColor'])if(!/^#[0-9a-f]{6}$/i.test(s[k]))s[k]=defaults[k];if(!fonts[s.font])s.font='sans';if(!['left','center','right'].includes(s.align))s.align='left'}
function syncLayerSelection(){prepareLayers(page());if(layerPageId!==page().id||!page().layerOrder.includes(selectedLayer)){selectedLayer='base';layerPageId=page().id}}
function activeLayer(){return selectedLayer==='base'?page():page().layers.find(l=>l.id===selectedLayer)||page()}
function textTarget(){syncLayerSelection();const l=activeLayer();return l.type==='image'?page():l}
function pageImages(p){return [p.image,...(p.layers||[]).filter(l=>l.type==='image').map(l=>l.image)].filter(Boolean)}
function layerName(l){return l===page()?'原有故事文字':l.type==='image'?(l.image?.name||'圖片'):l.type==='bubble'?'對話框':'文字方塊'}
function textNode(l){const box=document.createElement('div'),s=l.style;box.className='layer-content'+(l.type==='bubble'?' bubble':'');Object.assign(box.style,{width:'100%',height:'100%',fontFamily:fonts[s.font],fontSize:s.size/10.24+'cqw',color:s.color,lineHeight:s.lineHeight,textAlign:s.align,background:s.backdrop?s.boxColor+Math.round(s.boxOpacity*2.55).toString(16).padStart(2,'0'):'transparent',border:s.borderWidth/10.24+'cqw solid '+s.borderColor});for(const line of l.text.split('\n')){const para=document.createElement('p');para.textContent=line||'\u00a0';para.style.margin='0 0 '+s.paragraphGap/10.24+'cqw';box.append(para)}box.lastElementChild?.style.setProperty('margin-bottom','0');if(l.type==='bubble'){const tail=document.createElement('span');tail.className='bubble-tail';tail.style.borderTopColor=s.backdrop?s.boxColor+Math.round(s.boxOpacity*2.55).toString(16).padStart(2,'0'):s.borderColor;box.append(tail)}return box}
function positionLayer(el,l,index){const s=l.style;Object.assign(el.style,{position:'absolute',left:s.x+'%',top:s.y+'%',width:s.width+'%',height:s.height?s.height+'%':'auto',transform:'rotate('+s.rotation+'deg)',transformOrigin:'center',zIndex:String(index+1),display:l.type==='image'||(l.text&&s.showText!==false)?'block':'none'});}
function attachHandles(el,l,id){
  el.onpointerdown=e=>startLayerGesture(e,el,l,id,'move');
  el.onpointermove=e=>moveLayerGesture(e,el,l);
  el.onpointerup=el.onpointercancel=()=>{if(layerGesture){layerGesture=null;save();paintAllLayers()}};
  if(selectedLayer!==id)return;
  for(const [mode,label] of [['resize','調整圖層大小'],['rotate','旋轉圖層']]){const h=document.createElement('button');h.className='layer-handle '+mode;h.setAttribute('aria-label',label);h.onpointerdown=e=>startLayerGesture(e,el,l,id,mode);el.append(h)}
}
function startLayerGesture(e,el,l,id,mode){if(e.button!==0)return;e.preventDefault();e.stopPropagation();selectedLayer=id;const r=$('viewport').getBoundingClientRect(),b=el.getBoundingClientRect();layerGesture={mode,startX:e.clientX,startY:e.clientY,s:{...l.style},startHeight:el.offsetHeight/r.height*100,r,cx:b.x+b.width/2,cy:b.y+b.height/2,initialAngle:Math.atan2(e.clientY-(b.y+b.height/2),e.clientX-(b.x+b.width/2))};el.setPointerCapture(e.pointerId);document.querySelectorAll('.editable-layer').forEach(n=>n.classList.toggle('selected',n===el));renderLayerControls();syncTextControls()}
function moveLayerGesture(e,el,l){const g=layerGesture;if(!g)return;const dx=e.clientX-g.startX,dy=e.clientY-g.startY,s=l.style;if(g.mode==='move'){s.x=Math.max(0,Math.min(95,g.s.x+dx/g.r.width*100));s.y=Math.max(0,Math.min(95,g.s.y+dy/g.r.height*100))}else if(g.mode==='rotate'){s.rotation=Math.max(-180,Math.min(180,g.s.rotation+(Math.atan2(e.clientY-g.cy,e.clientX-g.cx)-g.initialAngle)*180/Math.PI))}else{const angle=g.s.rotation*Math.PI/180,localX=dx*Math.cos(angle)+dy*Math.sin(angle),localY=-dx*Math.sin(angle)+dy*Math.cos(angle);s.width=Math.max(2,Math.min(100,g.s.width+localX/g.r.width*100));if(l.type==='image'&&s.keepAspect!==false)s.height=Math.max(1,Math.min(100,g.s.height*s.width/g.s.width));else s.height=Math.max(2,Math.min(100,(g.s.height||g.startHeight)+localY/g.r.height*100))}positionLayer(el,l,page().layerOrder.indexOf(selectedLayer));renderLayerControls();syncTextControls()}
function syncTextControls(){const t=textTarget();$('storyText').value=t.text;for(const k of Object.keys(defaults)){if(typeof defaults[k]==='boolean')$(k).checked=t.style[k];else $(k).value=t.style[k]}}
function renderLayerControls(){
  const l=activeLayer(),s=l.style;for(const k of ['storyText','resetStyle',...Object.keys(defaults)])$(k).disabled=l.type==='image';$('selectedLayerName').textContent=layerName(l);const list=$('layerList');list.replaceChildren();for(const id of [...page().layerOrder].reverse()){const item=id==='base'?page():page().layers.find(l=>l.id===id),btn=document.createElement('button');btn.textContent=layerName(item);btn.className=id===selectedLayer?'selected':'';btn.onclick=()=>{selectedLayer=id;syncTextControls();paintAllLayers()};list.append(btn)}
  for(const [id,k] of [['layerX','x'],['layerY','y'],['layerWidth','width'],['layerHeight','height'],['layerRotation','rotation']])$(id).value=Math.round(s[k]*10)/10;
  $('layerAspect').checked=s.keepAspect!==false;$('layerAspect').disabled=l.type!=='image';$('removeLayer').disabled=selectedLayer==='base';const i=page().layerOrder.indexOf(selectedLayer);$('layerUp').disabled=i===page().layerOrder.length-1;$('layerDown').disabled=i===0;
}
function paintAllLayers(){
  syncLayerSelection();const p=page();if(!p.image)$('emptyArt').style.display=p.layers.length?'none':'flex';$('overlay').removeAttribute('style');$('overlay').className='editable-layer'+(selectedLayer==='base'?' selected':'');$('overlay').replaceChildren(textNode(p));positionLayer($('overlay'),p,p.layerOrder.indexOf('base'));attachHandles($('overlay'),p,'base');
  document.querySelectorAll('#scene > .extra-layer').forEach(n=>n.remove());const live=new Set();
  for(const l of p.layers){const el=document.createElement('div');el.className='extra-layer editable-layer'+(selectedLayer===l.id?' selected':'');el.setAttribute('aria-label',layerName(l));el.tabIndex=0;positionLayer(el,l,p.layerOrder.indexOf(l.id));if(l.type==='image'&&l.image){live.add(l.image.id);const img=document.createElement('img');img.alt=l.image.name;img.draggable=false;img.style.cssText='width:100%;height:100%;object-fit:contain;pointer-events:none';el.append(img);if(layerURLs.has(l.image.id))img.src=layerURLs.get(l.image.id);else getImageBlob(l.image).then(blob=>{if(!blob)throw Error('找不到圖層圖片');if(!img.isConnected)return;const url=URL.createObjectURL(blob);layerURLs.set(l.image.id,url);img.src=url}).catch(()=>toast('圖層圖片讀取失敗'))}else el.append(textNode(l));attachHandles(el,l,l.id);$('scene').append(el)}
  for(const [id,url] of layerURLs)if(!live.has(id)){URL.revokeObjectURL(url);layerURLs.delete(id)}renderLayerControls();
}
function addLayer(type,image,aspect=1){prepareLayers(page());const s={...defaults,...layerDefaults};if(type==='bubble'){s.borderWidth=2;s.boxOpacity=100;s.height=22}else if(type==='text')s.height=0;if(type==='image'){const [w,h]=book().pageSize.split('x').map(Number);s.width=30;s.height=Math.min(80,30*w/h/aspect)}const l={id:uid(),type,text:type==='bubble'?'你好！':type==='text'?'輸入文字':'',style:s,image};page().layers.push(l);page().layerOrder.push(l.id);selectedLayer=l.id;save();render()}
$('addTextLayer').onclick=()=>addLayer('text');$('addBubbleLayer').onclick=()=>addLayer('bubble');$('addImageLayer').onclick=()=>$('layerImageInput').click();
$('layerImageInput').onchange=async e=>{const file=e.target.files[0],target=page();e.target.value='';if(!file)return;if(!['image/png','image/jpeg','image/webp'].includes(file.type))return toast('請使用 PNG、JPEG 或 WebP');try{const bitmap=await createImageBitmap(file),aspect=bitmap.width/bitmap.height;bitmap.close();const ref={id:uid(),name:file.name,type:file.type};await imageStore('readwrite',s=>s.put(file,ref.id));if(page()!==target)return toast('頁面已切換，請在目標頁重新加入圖片');addLayer('image',ref,aspect)}catch(e){toast('無法加入圖片：'+e.message)}};
for(const [id,k] of [['layerX','x'],['layerY','y'],['layerWidth','width'],['layerHeight','height'],['layerRotation','rotation']])$(id).oninput=e=>{if(!e.target.validity.valid||e.target.value==='')return;const l=activeLayer(),s=l.style,v=+e.target.value;if(l.type==='image'&&s.keepAspect!==false&&['width','height'].includes(k)){const other=k==='width'?'height':'width';s[other]=Math.min(100,s[other]*v/(s[k]||1))}s[k]=v;save();paintAllLayers();syncTextControls()};
$('layerAspect').onchange=e=>{activeLayer().style.keepAspect=e.target.checked;save()};
for(const [id,delta] of [['layerUp',1],['layerDown',-1]])$(id).onclick=()=>{const order=page().layerOrder,i=order.indexOf(selectedLayer),j=i+delta;if(j<0||j>=order.length)return;[order[i],order[j]]=[order[j],order[i]];save();paintAllLayers()};
$('removeLayer').onclick=async()=>{const p=page(),id=selectedLayer;if(id==='base'||!await confirmDelete('刪除選取的圖層？'))return;p.layers=p.layers.filter(l=>l.id!==id);p.layerOrder=p.layerOrder.filter(x=>x!==id);selectedLayer='base';save();render()};
const HTML_LIMIT=50_000_000;
let lastExportURL;
async function exportImage(ref,w,h,quality,originals){let blob=originals.get(ref.id);if(!blob){blob=await getImageBlob(ref);if(!blob)throw Error('缺少圖片：'+ref.name);originals.set(ref.id,blob)}const bitmap=await createImageBitmap(blob),scale=Math.min(1,w/bitmap.width,h/bitmap.height);const canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(bitmap.width*scale));canvas.height=Math.max(1,Math.round(bitmap.height*scale));canvas.getContext('2d').drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();const compact=await new Promise(resolve=>canvas.toBlob(resolve,'image/webp',quality));canvas.width=canvas.height=1;if(!compact)throw Error('圖片壓縮失敗');return dataURL(compact)}
function buildReader(current,encoded){
 const slides=[];
 for(const p of current.pages){prepareLayers(p);const frame=document.createElement('section');frame.className='slide';if(p.image){const img=document.createElement('img');img.src=encoded.get(p.image.id);img.alt=p.title;img.style.cssText='position:absolute;inset:0;width:100%;height:100%;object-fit:'+p.fit;frame.append(img)}for(const [i,id] of p.layerOrder.entries()){const l=id==='base'?p:p.layers.find(l=>l.id===id),el=document.createElement('div');positionLayer(el,l,i);if(l.type==='image'&&l.image){const img=document.createElement('img');img.src=encoded.get(l.image.id);img.alt=l.image.name;img.style.cssText='width:100%;height:100%;object-fit:contain';el.append(img)}else el.append(textNode(l));frame.append(el)}slides.push(frame.outerHTML)}
 const title=document.createElement('span');title.textContent=current.title;const [w,h]=current.pageSize.split('x').map(Number);
 return `<!doctype html><html lang="zh-Hant"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${title.innerHTML}</title><style>*{box-sizing:border-box}body{margin:0;background:#eef1f5;font-family:system-ui;color:#233342}header{display:flex;align-items:center;justify-content:space-between;padding:16px;gap:12px;flex-wrap:wrap}button{padding:10px;border:1px solid #cad4e0;border-radius:8px;background:white}#frame{position:relative;container-type:inline-size;width:min(96vw,${w}px);aspect-ratio:${w}/${h};margin:20px auto;background:white;overflow:hidden}.slide{position:absolute;inset:0;display:none}.slide.active{display:block;animation:slide .25s ease-out}.layer-content{position:relative;padding:1.1cqw;border-radius:8px;white-space:pre-wrap;overflow-wrap:anywhere;overflow:hidden;box-sizing:border-box}.layer-content.bubble{border-radius:2cqw;overflow:visible}.bubble-tail{position:absolute;bottom:-1.8cqw;left:20%;width:0;height:0;border-left:1.5cqw solid transparent;border-right:.4cqw solid transparent;border-top:1.8cqw solid white}nav{display:flex;justify-content:center;align-items:center;gap:20px}@keyframes slide{from{transform:translateX(5%);opacity:.5}to{transform:translateX(0);opacity:1}}@media(prefers-reduced-motion:reduce){.slide.active{animation:none}}</style></head><body><header><strong>${title.innerHTML}</strong><span>尺寸已鎖定：${w} × ${h} px</span></header><main id="frame">${slides.join('')}</main><nav><button id="previous">← 上一頁</button><span id="count"></span><button id="following">下一頁 →</button></nav><script>const pages=[...document.querySelectorAll('.slide')];let i=0;function show(){pages.forEach((p,n)=>p.classList.toggle('active',n===i));document.getElementById('count').textContent=(i+1)+' / '+pages.length;document.getElementById('previous').disabled=i===0;document.getElementById('following').disabled=i===pages.length-1}document.getElementById('previous').onclick=()=>{if(i>0)i--;show()};document.getElementById('following').onclick=()=>{if(i<pages.length-1)i++;show()};show();</script></body></html>`;
}
$('exportHTML').onclick=async()=>{
 const button=$('exportHTML');button.disabled=true;
 try{const current=JSON.parse(JSON.stringify(book())),[w,h]=current.pageSize.split('x').map(Number),originals=new Map(),refs=new Map();for(const p of current.pages)for(const ref of pageImages(p))refs.set(ref.id,ref);let file;
 for(const quality of [.86,.7,.5]){const encoded=new Map();let i=0;for(const ref of refs.values()){button.textContent=`壓縮圖片 ${++i}/${refs.size}`;encoded.set(ref.id,await exportImage(ref,w,h,quality,originals))}file=new Blob([buildReader(current,encoded)],{type:'text/html;charset=utf-8'});if(file.size<=HTML_LIMIT)break}
 if(file.size>HTML_LIMIT)throw Error('壓縮後仍超過 50 MB，請減少圖片或頁數後再匯出。尺寸未更動，也未下載超額檔案。');
 if(lastExportURL)URL.revokeObjectURL(lastExportURL);lastExportURL=URL.createObjectURL(file);const a=document.createElement('a');a.href=lastExportURL;a.download=current.title+'.html';a.click();$('exportResult').replaceChildren();const link=document.createElement('a');link.href=lastExportURL;link.target='_blank';link.textContent=`開啟匯出預覽（${(file.size/1e6).toFixed(2)} MB · ${w} × ${h}）`;$('exportResult').append(link);toast(`HTML 已匯出，${(file.size/1e6).toFixed(2)} MB，尺寸已鎖定。`)
 }catch(e){toast('HTML 匯出失敗：'+e.message)}finally{button.disabled=false;button.textContent='匯出 HTML'}
};

startEditor();
